// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbw8VDOnYSnE97VSmxnE4s0ytehoM5gjw',
    appId: '1:985896803973:web:ccd34747795ad21cdf13ec',
    messagingSenderId: '985896803973',
    projectId: 'perfectswish-ai',
    authDomain: 'perfectswish-ai.firebaseapp.com',
    storageBucket: 'perfectswish-ai.firebasestorage.app',
    measurementId: 'G-N08Y5JENXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPDmhbBJAeevzQhl-Fp-gtjs9MDLkCMg',
    appId: '1:985896803973:android:9b66b533a130f6afdf13ec',
    messagingSenderId: '985896803973',
    projectId: 'perfectswish-ai',
    storageBucket: 'perfectswish-ai.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbw8VDOnYSnE97VSmxnE4s0ytehoM5gjw',
    appId: '1:985896803973:web:77eacfdb707f115edf13ec',
    messagingSenderId: '985896803973',
    projectId: 'perfectswish-ai',
    authDomain: 'perfectswish-ai.firebaseapp.com',
    storageBucket: 'perfectswish-ai.firebasestorage.app',
    measurementId: 'G-B9HHTHCWR4',
  );
}
